version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=codeping
      - POSTGRES_PASSWORD=codeping
      - POSTGRES_DB=codeping
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codeping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET:-mydevsecret}
      - DATABASE_URL=postgresql+asyncpg://codeping:codeping@db:5432/codeping
      - CELERY_ALWAYS_EAGER=true
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db-data: 